CREATE TABLE knowledge_articles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(191) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary VARCHAR(512) NOT NULL,
  content LONGTEXT NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT 'general',
  tags_json JSON DEFAULT NULL,
  aliases_json JSON DEFAULT NULL,
  plant_types_json JSON DEFAULT NULL,
  problem_types_json JSON DEFAULT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'admin',
  source_ref VARCHAR(255) DEFAULT NULL,
  source_title VARCHAR(255) DEFAULT NULL,
  source_publisher VARCHAR(255) DEFAULT NULL,
  source_updated_at VARCHAR(32) DEFAULT NULL,
  source_url VARCHAR(1024) DEFAULT NULL,
  source_id VARCHAR(128) DEFAULT NULL,
  content_updated_at DATE DEFAULT NULL,
  reviewed_at DATETIME DEFAULT NULL,
  reviewed_by VARCHAR(128) DEFAULT NULL,
  image_license VARCHAR(255) DEFAULT NULL,
  image_source_url VARCHAR(1024) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_knowledge_articles_slug (slug),
  KEY idx_knowledge_articles_status_sort (status, sort_order, id),
  KEY idx_knowledge_articles_category (category, status),
  FULLTEXT KEY ft_knowledge_articles_text (title, summary, content)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admin_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'operator',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_admin_users_username (username),
  KEY idx_admin_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
