const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

test('resident-service docs and runtime-service docs are present and linked', () => {
  const repoRoot = path.resolve(__dirname, '..');
  const splitPlanPath = path.join(repoRoot, 'docs', 'resident-service-split-plan.md');
  const envMatrixPath = path.join(repoRoot, 'docs', 'trial-environment-variable-matrix.md');
  const interfaceDraftPath = path.join(repoRoot, 'docs', 'resident-service-interface-draft.md');
  const migrationMapPath = path.join(repoRoot, 'docs', 'runtime-service-migration-map.md');
  const rolloutChecklistPath = path.join(repoRoot, 'docs', 'runtime-service-rollout-checklist.md');
  const deploymentChecklistPath = path.join(repoRoot, 'docs', 'trial-deployment-checklist.md');
  const acceptanceChecklistPath = path.join(repoRoot, 'docs', 'trial-acceptance-checklist.md');
  const readinessGapPath = path.join(repoRoot, 'docs', 'trial-readiness-gap-assessment.md');
  const firstAcceptanceRecordPath = path.join(repoRoot, 'docs', 'first-trial-acceptance-record-template.md');
  const firstAcceptanceSamplePath = path.join(repoRoot, 'docs', 'first-trial-acceptance-record-sample.md');
  const currentGoalAuditPath = path.join(repoRoot, 'docs', 'current-goal-completion-audit-summary.md');
  const dailyOpsChecklistPath = path.join(repoRoot, 'docs', 'daily-trial-ops-checklist.md');
  const weeklyReportTemplatePath = path.join(repoRoot, 'docs', 'trial-weekly-report-template.md');
  const incidentReviewTemplatePath = path.join(repoRoot, 'docs', 'incident-review-template.md');
  const capacityBaselinePath = path.join(repoRoot, 'docs', 'trial-capacity-baseline.md');
  const scaleStagePlanPath = path.join(repoRoot, 'docs', 'trial-scale-stage-plan.md');
  const stagedScalingGuidePath = path.join(repoRoot, 'docs', 'staged-deployment-and-scaling-guide.md');
  const nextStagePlanPath = path.join(repoRoot, 'docs', 'next-stage-optimization-plan.md');
  const fourWeekPlanPath = path.join(repoRoot, 'docs', 'four-week-trial-execution-plan.md');
  const runtimeServiceReadmePath = path.join(repoRoot, 'runtime-service', 'README.md');
  const minimalMonitoringPath = path.join(repoRoot, 'docs', 'minimal-monitoring-checks.md');
  const runtimeServiceEnvPath = path.join(repoRoot, 'runtime-service', '.env.example');
  const latestSamplePath = path.join(repoRoot, 'reference', 'runtime-device-latest.sample.json');
  const commandSendSamplePath = path.join(repoRoot, 'reference', 'runtime-device-command-send.sample.json');
  const docsIndexPath = path.join(repoRoot, 'docs', 'README.md');
  const rootReadmePath = path.join(repoRoot, 'README.md');

  const splitPlan = fs.readFileSync(splitPlanPath, 'utf8');
  const envMatrix = fs.readFileSync(envMatrixPath, 'utf8');
  const interfaceDraft = fs.readFileSync(interfaceDraftPath, 'utf8');
  const migrationMap = fs.readFileSync(migrationMapPath, 'utf8');
  const rolloutChecklist = fs.readFileSync(rolloutChecklistPath, 'utf8');
  const deploymentChecklist = fs.readFileSync(deploymentChecklistPath, 'utf8');
  const acceptanceChecklist = fs.readFileSync(acceptanceChecklistPath, 'utf8');
  const readinessGap = fs.readFileSync(readinessGapPath, 'utf8');
  const firstAcceptanceRecord = fs.readFileSync(firstAcceptanceRecordPath, 'utf8');
  const firstAcceptanceSample = fs.readFileSync(firstAcceptanceSamplePath, 'utf8');
  const currentGoalAudit = fs.readFileSync(currentGoalAuditPath, 'utf8');
  const weeklyReportTemplate = fs.readFileSync(weeklyReportTemplatePath, 'utf8');
  const incidentReviewTemplate = fs.readFileSync(incidentReviewTemplatePath, 'utf8');
  const capacityBaseline = fs.readFileSync(capacityBaselinePath, 'utf8');
  const scaleStagePlan = fs.readFileSync(scaleStagePlanPath, 'utf8');
  const stagedScalingGuide = fs.readFileSync(stagedScalingGuidePath, 'utf8');
  const nextStagePlan = fs.readFileSync(nextStagePlanPath, 'utf8');
  const fourWeekPlan = fs.readFileSync(fourWeekPlanPath, 'utf8');
  const dailyOpsChecklist = fs.readFileSync(dailyOpsChecklistPath, 'utf8');
  const runtimeServiceReadme = fs.readFileSync(runtimeServiceReadmePath, 'utf8');
  const minimalMonitoring = fs.readFileSync(minimalMonitoringPath, 'utf8');
  const runtimeServiceEnv = fs.readFileSync(runtimeServiceEnvPath, 'utf8');
  const latestSample = fs.readFileSync(latestSamplePath, 'utf8');
  const commandSendSample = fs.readFileSync(commandSendSamplePath, 'utf8');
  const docsIndex = fs.readFileSync(docsIndexPath, 'utf8');
  const rootReadme = fs.readFileSync(rootReadmePath, 'utf8');

  assert.match(splitPlan, /Device Runtime Service/);
  assert.match(envMatrix, /Trial Environment Variable Matrix/);
  assert.match(envMatrix, /MYSQL_DSN/);
  assert.match(envMatrix, /API_SCF_RUNTIME_PROXY_ENABLED/);
  assert.match(interfaceDraft, /\/runtime\/ingest\/message/);
  assert.match(migrationMap, /Runtime Service Migration Map/);
  assert.match(migrationMap, /ScfApiAdapter\.js/);
  assert.match(migrationMap, /POST \/runtime\/device\/latest/);
  assert.match(migrationMap, /POST \/runtime\/device\/command\/send/);
  assert.match(rolloutChecklist, /Runtime Service Trial Rollout Checklist/);
  assert.match(rolloutChecklist, /INGEST_SCF_RUNTIME_PROXY_ENABLED/);
  assert.match(rolloutChecklist, /API_SCF_RUNTIME_PROXY_ROUTES/);
  assert.match(rolloutChecklist, /runtime_query_latest/);
  assert.match(rolloutChecklist, /cacheMeta\.mode/);
  assert.match(deploymentChecklist, /Trial Deployment Checklist/);
  assert.match(deploymentChecklist, /runtime-service/);
  assert.match(deploymentChecklist, /Redis/);
  assert.match(deploymentChecklist, /cacheMeta\.latestSource/);
  assert.match(deploymentChecklist, /cache_only_injected/);
  assert.match(acceptanceChecklist, /Trial Acceptance Checklist/);
  assert.match(acceptanceChecklist, /accepted_with_limits/);
  assert.match(readinessGap, /Trial Readiness Gap Assessment/);
  assert.match(readinessGap, /preparing for accepted_with_limits/);
  assert.match(readinessGap, /real-device proof/);
  assert.match(firstAcceptanceRecord, /First Trial Acceptance Record Template/);
  assert.match(firstAcceptanceRecord, /Acceptance verdict/);
  assert.match(firstAcceptanceRecord, /runtime-service structured logs available/);
  assert.match(firstAcceptanceSample, /First Trial Acceptance Record Sample/);
  assert.match(firstAcceptanceSample, /accepted_with_limits/);
  assert.match(firstAcceptanceSample, /ingest proxy: disabled/);
  assert.match(currentGoalAudit, /Current Goal Completion Audit Summary/);
  assert.match(currentGoalAudit, /implemented but not live-verified/);
  assert.match(currentGoalAudit, /operational blockers/);
  assert.match(weeklyReportTemplate, /Trial Weekly Report Template/);
  assert.match(weeklyReportTemplate, /Capacity and concurrency observation/);
  assert.match(incidentReviewTemplate, /Incident Review Template/);
  assert.match(incidentReviewTemplate, /Root cause analysis/);
  assert.match(capacityBaseline, /Trial Capacity Baseline/);
  assert.match(capacityBaseline, /runtime-load-smoke\.js/);
  assert.match(capacityBaseline, /SCF is good for early validation/);
  assert.match(scaleStagePlan, /Trial Scale Stage Plan/);
  assert.match(scaleStagePlan, /1000 devices/);
  assert.match(scaleStagePlan, /move the hottest runtime logic out of SCF first/);
  assert.match(stagedScalingGuide, /Staged Deployment and Scaling Guide/);
  assert.match(stagedScalingGuide, /10000 devices/);
  assert.match(stagedScalingGuide, /runtime-service/);
  assert.match(nextStagePlan, /Next-Stage Optimization Plan/);
  assert.match(nextStagePlan, /P0 work package/);
  assert.match(nextStagePlan, /Definition of success for this stage/);
  assert.match(fourWeekPlan, /Four-Week Trial Execution Plan/);
  assert.match(fourWeekPlan, /Week 1 — close the core data model/);
  assert.match(fourWeekPlan, /Week 4 — controlled trial enablement/);
  assert.match(dailyOpsChecklist, /Daily Trial Ops Checklist/);
  assert.match(dailyOpsChecklist, /runtime_proxy_failed/);
  assert.match(runtimeServiceReadme, /Runtime Service Scaffold/i);
  assert.match(runtimeServiceReadme, /\/runtime\/device\/command\/send/);
  assert.match(runtimeServiceReadme, /\/runtime\/device\/command\/detail/);
  assert.match(runtimeServiceReadme, /runtime_ingest/);
  assert.match(runtimeServiceReadme, /cache_merged/);
  assert.match(minimalMonitoring, /runtime-service structured log supplement/);
  assert.match(minimalMonitoring, /runtime_query_latest/);
  assert.match(minimalMonitoring, /cache_merged/);
  assert.match(runtimeServiceEnv, /STORAGE_BACKEND=memory/);
  assert.match(runtimeServiceEnv, /COMMAND_PROVIDER_BACKEND=mock/);
  assert.match(latestSample, /demo-device-001/);
  assert.match(commandSendSample, /watering/);
  assert.match(docsIndex, /resident-service-split-plan\.md/);
  assert.match(docsIndex, /trial-environment-variable-matrix\.md/);
  assert.match(docsIndex, /resident-service-interface-draft\.md/);
  assert.match(docsIndex, /runtime-service-migration-map\.md/);
  assert.match(docsIndex, /runtime-service-rollout-checklist\.md/);
  assert.match(docsIndex, /trial-deployment-checklist\.md/);
  assert.match(docsIndex, /trial-acceptance-checklist\.md/);
  assert.match(docsIndex, /trial-readiness-gap-assessment\.md/);
  assert.match(docsIndex, /first-trial-acceptance-record-template\.md/);
  assert.match(docsIndex, /first-trial-acceptance-record-sample\.md/);
  assert.match(docsIndex, /current-goal-completion-audit-summary\.md/);
  assert.match(docsIndex, /daily-trial-ops-checklist\.md/);
  assert.match(docsIndex, /trial-weekly-report-template\.md/);
  assert.match(docsIndex, /incident-review-template\.md/);
  assert.match(docsIndex, /trial-capacity-baseline\.md/);
  assert.match(docsIndex, /trial-scale-stage-plan\.md/);
  assert.match(docsIndex, /staged-deployment-and-scaling-guide\.md/);
  assert.match(docsIndex, /next-stage-optimization-plan\.md/);
  assert.match(docsIndex, /four-week-trial-execution-plan\.md/);
  assert.match(docsIndex, /runtime-service\/README\.md/);
  assert.match(rootReadme, /resident-service-split-plan\.md/);
  assert.match(rootReadme, /trial-environment-variable-matrix\.md/);
  assert.match(rootReadme, /resident-service-interface-draft\.md/);
  assert.match(rootReadme, /runtime-service-migration-map\.md/);
  assert.match(rootReadme, /runtime-service-rollout-checklist\.md/);
  assert.match(rootReadme, /trial-deployment-checklist\.md/);
  assert.match(rootReadme, /trial-acceptance-checklist\.md/);
  assert.match(rootReadme, /trial-readiness-gap-assessment\.md/);
  assert.match(rootReadme, /first-trial-acceptance-record-template\.md/);
  assert.match(rootReadme, /first-trial-acceptance-record-sample\.md/);
  assert.match(rootReadme, /current-goal-completion-audit-summary\.md/);
  assert.match(rootReadme, /daily-trial-ops-checklist\.md/);
  assert.match(rootReadme, /trial-weekly-report-template\.md/);
  assert.match(rootReadme, /incident-review-template\.md/);
  assert.match(rootReadme, /trial-capacity-baseline\.md/);
  assert.match(rootReadme, /trial-scale-stage-plan\.md/);
  assert.match(rootReadme, /staged-deployment-and-scaling-guide\.md/);
  assert.match(rootReadme, /next-stage-optimization-plan\.md/);
  assert.match(rootReadme, /four-week-trial-execution-plan\.md/);
  assert.match(rootReadme, /runtime-service\/README\.md/);
});
